const data ={
    products:[
        {
        _id: '1',
        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image:'https://newamazona-final.herokuapp.com/images/p1.jpg',
        price: 66, countInStock: 0,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
    },
    {
        _id: '2',
        name: 'Adidas Slim Shirt',
        category: 'Shirts',
        image:'https://newamazona-final.herokuapp.com/images/p2.jpg',
        price: 80, countInStock: 10,
        brand: 'Adiddas',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
    },
    {
        _id: '3',
        name: 'Lacoste Slim Shirt',
        category: 'Pants',
        image:'https://newamazona-final.herokuapp.com/images/p3.jpg',
        price: 79, countInStock: 5,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
    },
    {
        _id: '4',
        name: 'Gucci Slim Pant',
        category: 'Pants',
        image:'https://newamazona-final.herokuapp.com/images/p4.jpg',
        price: 90, countInStock: 10,
        brand: 'Gucci',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
    },
    {
        _id: '5',
        name: 'George Armani Slim Pant',
        category: 'Pants',
        image:'https://newamazona-final.herokuapp.com/images/p5.jpg',
        price: 50, countInStock: 0,
        brand: 'Armani',
        rating: 5,
        numReviews: 20,
        description: 'high quality product',
    },
    {
        _id: '6',
        name: 'Prada Fit Pant',
        category: 'Pants',
        image:'https://newamazona-final.herokuapp.com/images/p6.jpg',
        price: 90, countInStock: 5,
        brand: 'Nike',
        rating: 4.0,
        numReviews: 17,
        description: 'high quality product',
    },

    ],
};
export default data;